### ISSUE TITLE
Support for unconventional Sourcegraph URLs

### ISSUE THREAD

**Issue by jasonhawkharris** [tjdevries/sg.nvim#13] opened 2023-02-07 11:42 UTC
Enhance pattern matching for different URLs. 
- https://sourcegraph.com works.
- https://mysgurl.dev.org does not.

**Comment by Ajetski** [comment] 2023-02-07 21:52
This is a duplicate of #11. Also see #12 for a PR that has begun work on this

**Comment by jasonhawkharris** [comment] 2023-02-11 22:40
Closing because the is a duplicate on #11

**Closed** 2023-02-11 22:40 UTC
